In [2]:
import pandas as pd
import numpy as np

In [7]:
data = np.random.random(size = (10000,3))
print(data)
df = pd.DataFrame(data=data, columns=["A", "B", "C"])
df.head()

[[0.66406424 0.20308325 0.33078853]
 [0.12212722 0.26470763 0.22474489]
 [0.77891216 0.45292414 0.27126611]
 ...
 [0.53540067 0.78779228 0.21524879]
 [0.01103323 0.01839735 0.58224906]
 [0.42826233 0.90671028 0.1462591 ]]


A         B         C
0  0.664064  0.203083  0.330789
1  0.122127  0.264708  0.224745
2  0.778912  0.452924  0.271266
3  0.714060  0.625821  0.593438
4  0.746553  0.356565  0.479473

In [10]:
df.to_csv("save.csv", index = False, float_format="%0.4f")

In [11]:
df.to_pickle("save.pkl")